builds:
  - main: ./starport/interface/cli/starport
    ldflags:
      - -s -w -X github.com/tendermint/starport/starport/internal/version.Version={{.Tag}} -X github.com/tendermint/starport/starport/internal/version.Date={{.Date}}
    goarch:
      - amd64
      - arm64


brews:
  - name: "starport"
    description: "CLI tool for developing Cosmos SDK apps."
    homepage: "https://github.com/tendermint/starport"
    github:
      owner: "tendermint"
      name: "homebrew-tap"
    install: |
      bin.install "starport"

snapcrafts:
    replacements:
      darwin: macOS
    summary: The easiest way to build a blockchain.
    description: Starport is the easiest way to build blockchains. It is a developer-friendly interface to the Cosmos SDK, the world's most widely-used blockchain application framework. Starport generates boilerplate code for you, so you can focus on writing business logic.
    grade: devel
    confinement: classic
    base: core18
    license: Apache-2.0
    apps:
      starport:
        plugs: ["home", "personal-files", "network", "network-bind"]
        command: bin/starport
